name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Build Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: |
            build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      CLOUDSDK_PYTHON_SITEPACKAGES: 1 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
      - name: Install NumPy
        run: |
          # Dynamically find the python interpreter used by this gcloud installation
          GCLOUD_PYTHON=$(gcloud info --format="value(basic.python_location)")
          
          echo "Installing NumPy using: $GCLOUD_PYTHON"
          "$GCLOUD_PYTHON" -m pip install numpy
      - name: Stop Production Server
        uses: google-github-actions/ssh-compute@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          zone: ${{ secrets.GCP_VM_ZONE }}
          instance_name: ${{ secrets.GCP_VM_NAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          user: ${{ secrets.USERNAME }}
          command: |
              pm2 list
              pm2 stop mafia-bot
              cd ../${{ secrets.USERNAME }}/MafiaBot
              sudo rm -rf build
      - name: Transfer Build to Production Server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/google_compute_engine
          chmod 600 ~/.ssh/google_compute_engine
          echo "$PUBLIC_KEY" > ~/.ssh/google_compute_engine.pub
          chmod 600 ~/.ssh/google_compute_engine.pub
          gcloud compute scp --recurse ./build/* \
            ${{ secrets.USERNAME }}@${{ secrets.GCP_VM_NAME }}:~/MafiaBot/build \
            --zone=${{ secrets.GCP_VM_ZONE }} \
            --tunnel-through-iap \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --ssh-key-file=~/.ssh/google_compute_engine   
      - name: Start Production Server
        uses: google-github-actions/ssh-compute@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          zone: ${{ secrets.GCP_VM_ZONE }}
          instance_name: ${{ secrets.GCP_VM_NAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          user: ${{ secrets.USERNAME }}
          command: |
              cd ../${{ secrets.USERNAME }}/MafiaBot
              git restore .
              git pull origin main
              sudo npm i
              pm2 restart mafia-bot


