name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Build Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: |
            build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [BAG_HOST]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
      - name: Stop Production Server
        uses: google-github-actions/ssh-compute@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          zone: ${{ secrets.GCP_VM_ZONE }}
          instance_name: ${{ secrets.GCP_VM_NAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
              pm2 list
              pm2 stop mafia-bot
              cd ../aqealejandro/MafiaBot
              sudo rm -rf build
      - name: Transfer Build to Production Server
        run: |
          # Create a secure .ssh directory and write the secret to a file
          mkdir -p ~/.ssh
          
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/google_compute_engine
          chmod 600 ~/.ssh/google_compute_engine
          
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/google_compute_engine.pub
          chmod 600 ~/.ssh/google_compute_engine.pub
          
          # --recurse handles directories like your ./build/. source
          # --tunnel-through-iap bypasses the need for a static/public IP
          gcloud compute scp --recurse ./build/* \
            ${{ secrets.GCP_VM_NAME }}:~/MafiaBot \
            --zone=${{ secrets.GCP_VM_ZONE }} \
            --tunnel-through-iap \
            --project=${{ secrets.GCP_PROJECT_ID }}
            --ssh-key-file=~/.ssh/google_compute_engine
      - name: Start Production Server
        uses: google-github-actions/ssh-compute@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          zone: ${{ secrets.GCP_VM_ZONE }}
          instance_name: ${{ secrets.GCP_VM_NAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
              cd ../aqealejandro/MafiaBot
              git restore .
              git pull origin main
              npm i
              pm2 restart mafia-bot


